test_that("em_model_registry defines 2PL and 1PL", {
  r2 <- em_model_registry("2PL")
  expect_equal(r2$parnames, c("a", "nu"))
  expect_true(r2$est[["a"]] && r2$est[["nu"]])
  expect_equal(unname(r2$start), c(1, 0))
  expect_equal(unname(r2$lower), c(0.1, -10))
  expect_equal(unname(r2$upper), c(10, 10))
  r1 <- em_model_registry("1PL")
  expect_false(r1$est[["a"]])
  expect_true(r1$est[["nu"]])
  expect_error(em_model_registry("4PL"), "should be one of")
})

test_that("the registry and parmap cover the 3PL", {
  r3 <- em_model_registry("3PL")
  expect_equal(r3$parnames, c("a", "nu", "c"))
  expect_true(all(r3$est))
  expect_equal(unname(r3$lower), c(0.1, -10, 0.001))
  expect_equal(unname(r3$upper), c(10, 10, 0.5))
  pm <- em_parmap_separate(c("i1", "i2"), "3PL")
  expect_equal(nrow(pm), 6L)
  expect_equal(pm$parname, rep(c("a", "nu", "c"), 2L))
  expect_equal(pm$parindex, 1:6)
  # 2PL layout unchanged
  pm2 <- em_parmap_separate(c("i1", "i2"), "2PL")
  expect_equal(nrow(pm2), 4L)
})

test_that("em_parmap_separate builds the per-item map", {
  pm <- em_parmap_separate(c("i1", "i2"), "2PL")
  expect_equal(nrow(pm), 4L)
  expect_equal(pm$item, c("i1", "i1", "i2", "i2"))
  expect_equal(pm$parname, rep(c("a", "nu"), 2L))
  expect_true(all(pm$group == 1L))
  expect_true(all(pm$est))
  expect_equal(pm$parindex, 1:4)
  pm1 <- em_parmap_separate(c("i1", "i2"), "1PL")
  expect_equal(pm1$est, c(FALSE, TRUE, FALSE, TRUE))
  expect_equal(pm1$parindex, c(NA, 1L, NA, 2L))
  expect_equal(sum(pm1$est), 2L)
})
