// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// em_mstep_items_cpp
List em_mstep_items_cpp(NumericVector theta, NumericMatrix njk, NumericMatrix rjk, NumericVector a, NumericVector nu, LogicalVector est_a, NumericVector lower_a, NumericVector upper_a, NumericVector lower_nu, NumericVector upper_nu, int inner_maxit, double inner_tol);
RcppExport SEXP _irtlink_em_mstep_items_cpp(SEXP thetaSEXP, SEXP njkSEXP, SEXP rjkSEXP, SEXP aSEXP, SEXP nuSEXP, SEXP est_aSEXP, SEXP lower_aSEXP, SEXP upper_aSEXP, SEXP lower_nuSEXP, SEXP upper_nuSEXP, SEXP inner_maxitSEXP, SEXP inner_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type njk(njkSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type rjk(rjkSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type est_a(est_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lower_a(lower_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper_a(upper_aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lower_nu(lower_nuSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type upper_nu(upper_nuSEXP);
    Rcpp::traits::input_parameter< int >::type inner_maxit(inner_maxitSEXP);
    Rcpp::traits::input_parameter< double >::type inner_tol(inner_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(em_mstep_items_cpp(theta, njk, rjk, a, nu, est_a, lower_a, upper_a, lower_nu, upper_nu, inner_maxit, inner_tol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_irtlink_em_mstep_items_cpp", (DL_FUNC) &_irtlink_em_mstep_items_cpp, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_irtlink(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
