# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em_mstep_items_cpp <- function(theta, njk, rjk, a, nu, est_a, lower_a, upper_a, lower_nu, upper_nu, inner_maxit, inner_tol) {
    .Call(`_irtlink_em_mstep_items_cpp`, theta, njk, rjk, a, nu, est_a, lower_a, upper_a, lower_nu, upper_nu, inner_maxit, inner_tol)
}

